import type { Metadata } from "next";
import { Montserrat as CustomFont } from "next/font/google";
import { Silkscreen } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import "./globals.css";

// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const customFont = CustomFont({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "Ayush Singh",
  keywords:
    "Portfolio Ayush Singh Ayush AyushSingh ayush singh ayushsingh-ayushsingh",
  category: "Best Portfolio Website",
  authors: [
    { name: "Ayush Singh", url: "https://portfolio.ayushpno.workers.dev/" },
  ],
  openGraph: {
    type: "website",
    url: "portfolio.ayushsingh.workers.dev",
    title: "Ayush Singh - Portfolio",
    description:
      "Ayush Singh, AI ready full-stack software developer from Bhopal, M.P., India.",
    siteName: "portfolio.ayushsingh.workers.dev",
    images: [{ url: "https://example.com/og.png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${customFont.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster className="dark:invert-95 select-none" />
        </ThemeProvider>
      </body>
    </html>
  );
}
